version: "3"
services:
  databse:
    image: "mongo:2.6.12"
    container_name: "dev-mongodb"
#    environment:
#      - MONGO_INITDB_DATABASE=liqiang
#      - MONGO_INITDB_ROOT_USERNAME=liuliqiang
#      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
    - /mnt/volume2/data/mongod:/data/db
    ports:
    - "27017-27019:27017-27019"
